"""fix created_at default value

Revision ID: 4de943be95d1
Revises: 2ce5269869b7
Create Date: 2025-11-23 00:07:48.837475

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4de943be95d1"
down_revision: Union[str, Sequence[str], None] = "2ce5269869b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dog_photo_stats", "views", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "dog_photo_stats",
        "last_viewed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("dog_photo_stats_photo_id_key"), "dog_photo_stats", type_="unique")
    op.create_index(op.f("ix_dog_photo_stats_id"), "dog_photo_stats", ["id"], unique=False)
    op.drop_constraint(op.f("dog_photo_stats_photo_id_fkey"), "dog_photo_stats", type_="foreignkey")
    op.create_foreign_key(None, "dog_photo_stats", "dog_photos", ["photo_id"], ["id"])
    op.alter_column("dog_photos", "breed", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column(
        "dog_photos",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "dog_photos",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_dog_photos_breed"), table_name="dog_photos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_dog_photos_breed"), "dog_photos", ["breed"], unique=False)
    op.alter_column(
        "dog_photos",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "dog_photos",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column("dog_photos", "breed", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.drop_constraint(None, "dog_photo_stats", type_="foreignkey")
    op.create_foreign_key(
        op.f("dog_photo_stats_photo_id_fkey"), "dog_photo_stats", "dog_photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_dog_photo_stats_id"), table_name="dog_photo_stats")
    op.create_unique_constraint(
        op.f("dog_photo_stats_photo_id_key"), "dog_photo_stats", ["photo_id"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "dog_photo_stats",
        "last_viewed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column("dog_photo_stats", "views", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
