"""create dog photos

Revision ID: cfce76ad9531
Revises:
Create Date: 2025-11-22 23:54:27.605732

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfce76ad9531"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dog_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("breed", sa.String(length=50), nullable=True),
        sa.Column("sub_breed", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dog_photos_breed"), "dog_photos", ["breed"], unique=False)
    op.create_index(op.f("ix_dog_photos_id"), "dog_photos", ["id"], unique=False)
    op.create_table(
        "dog_photo_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("last_viewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["photo_id"], ["dog_photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("photo_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dog_photo_stats")
    op.drop_index(op.f("ix_dog_photos_id"), table_name="dog_photos")
    op.drop_index(op.f("ix_dog_photos_breed"), table_name="dog_photos")
    op.drop_table("dog_photos")
    # ### end Alembic commands ###
